version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: 
      context: ./kafka-docker-master
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  nodejs:
    build:
      context: ./TaskWebApp/src/main/resources/static/js/nodeJS
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    ports:
      - '9097:9097'

      
  publisher:
    image: publisher
    container_name: publisher
    build:
      context: ./publisher
      dockerfile: Dockerfile
    ports:
     - '9091:9091'
    depends_on:
     - kafka
     - zookeeper
     
  consumer:
    image: consumer
    container_name: consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
     - '9093:9093'
    depends_on:
     - postgres
     - kafka
     - zookeeper   
  
  task-web-app:
    image: task-web-app
    container_name: task-web-app
    build:
      context: ./TaskWebApp
      dockerfile: Dockerfile
    ports:
     - '9090:9090'
    depends_on:
     - postgres
     
     
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=consumer
    expose:
     - 5432
    ports:
     - 5432:5432
   
volumes:
  db-data:                